<a href="https://colab.research.google.com/github/Sithija97/Python-Projects/blob/main/module_02_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving module_2.xlsx to module_2.xlsx

In [ ]:
# reading the csv file
df = pd.read_excel("module_2.xlsx",index_col=False)

In [ ]:
df

,fv.st.hp,fv.bl.hp,fv.ds.hp,fv.im.hp,fv.ft.hp,fsv.st.ba,fsv.st.tha,fsv.st.bha,fsv.st.ff.ka,fsv.st.bf.ka,...,bsv.im.hip.a,bsv.ft.ba,bsv.ft.tha,bsv.ft.bha,bsv.ft.ff.ka,bsv.ft.bf.ka,bsv.ft.hip.a,player,shot,correctness
0,1,1,1,1,1,26.522275,175.880343,171.149777,168.745427,172.287051,...,162.264251,0.000000,113.345479,107.445714,154.701123,167.084491,168.794345,1,back foot drive,0
1,1,1,1,1,1,26.522275,175.880343,174.149777,168.745427,174.287051,...,162.264251,0.000000,112.345479,105.445714,154.701123,168.084491,169.794345,1,back foot drive,0
2,1,1,1,1,1,28.533375,176.260343,172.188777,167.475427,171.087051,...,164.264251,0.000000,112.345479,105.445714,151.701123,164.084491,167.794345,1,back foot drive,0
3,1,1,1,1,1,26.522275,176.260343,171.149777,169.745427,172.087051,...,161.264251,0.000000,114.345479,107.445714,154.701123,166.084491,169.794345,1,back foot drive,0
4,1,1,1,1,1,27.533375,175.880343,170.249777,168.745427,172.087051,...,163.264251,0.000000,112.345479,106.445714,153.701123,167.084491,167.794345,1,back foot drive,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,1,1,1,1,1,34.456319,171.260633,169.888323,170.741234,169.546227,...,169.243327,0.000000,295.921692,0.000000,169.876313,174.015762,178.289155,1,cut,1
297,1,1,1,1,1,44.049224,179.600701,179.620083,177.785231,183.120230,...,176.014743,69.022666,354.509848,9.225897,147.151989,181.945860,180.220420,1,pull,1
298,1,1,1,1,1,35.049224,170.600701,170.620083,178.785231,174.120230,...,167.014743,60.022666,345.509848,0.225897,139.151989,172.945860,171.220420,1,pull,1
299,1,1,1,1,1,30.686650,194.834498,179.494779,167.341543,184.958215,...,159.910785,0.000000,35.903286,299.966121,101.253823,91.247889,157.250527,4,sweep,1
300,1,1,1,1,1,21.686650,185.834498,170.494779,158.341543,175.958215,...,150.910785,0.000000,26.903286,290.966121,92.253823,82.247889,148.250527,4,sweep,1

In [ ]:
df.rename(columns = {'correctness':'accuracy'}, inplace=1)

In [ ]:
# average numbers for all columns
df.groupby('shot').mean()

,fv.st.hp,fv.bl.hp,fv.ds.hp,fv.im.hp,fv.ft.hp,fsv.st.ba,fsv.st.tha,fsv.st.bha,fsv.st.ff.ka,fsv.st.bf.ka,...,bsv.im.bf.ka,bsv.im.hip.a,bsv.ft.ba,bsv.ft.tha,bsv.ft.bha,bsv.ft.ff.ka,bsv.ft.bf.ka,bsv.ft.hip.a,player,accuracy
shot,,,,,,,,,,,,,,,,,,,,,
back foot deffence,1.000000,1.000000,1.000000,1.000000,1.000000,27.482077,176.581098,1.716026e+02,168.537880,172.087051,...,168.919358,163.566138,0.000000,92.273729,78.180757,151.666772,164.591754,165.181201,1.000000,0.113208
back foot drive,1.000000,1.000000,1.000000,1.000000,1.000000,27.535591,176.509148,1.719293e+02,168.229547,172.412672,...,168.728173,163.663682,2.410105,112.450956,106.958676,154.722795,166.327720,168.206410,1.055556,0.111111
cut,1.000000,1.000000,1.000000,1.000000,1.000000,37.457630,175.507692,1.010576e+12,173.154646,172.774462,...,172.878975,172.349209,0.000000,299.327574,10.660586,173.935137,177.074586,178.465626,1.000000,0.823529
front foot defence,0.493333,0.746667,0.746667,0.240000,0.240000,22.948701,172.638991,1.745847e+02,172.699917,179.878415,...,162.579411,162.811558,50.055499,106.258523,113.010160,147.232055,162.091411,162.850118,4.040000,0.200000
front foot drive,0.537313,0.716418,0.716418,0.537313,0.268657,21.806089,174.605519,1.754444e+02,171.790403,179.141180,...,162.936479,162.998807,97.564545,83.071491,104.083597,146.533031,160.105011,162.005619,3.925373,0.208955
pull,1.000000,1.000000,1.000000,1.000000,1.000000,38.921006,173.478481,1.737096e+02,171.988543,177.945226,...,158.420547,168.000704,59.491921,348.449377,2.667838,142.248089,174.888272,169.287732,1.000000,0.823529
sweep,0.944444,1.000000,0.944444,0.944444,0.944444,24.263775,188.463947,1.736357e+02,162.026284,179.292375,...,85.252393,151.469706,0.000000,46.063971,294.754700,106.617876,85.801824,150.452080,4.055556,0.722222

In [ ]:
# drop missing values if exist
df=df.dropna(how="any")
print(df.shape)

(295, 68)

In [ ]:
# determining inputs and target
inputs = df.drop(columns = ['shot','accuracy'])
target = df[['accuracy']]

In [ ]:
# split the dataset into train and test subsets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,train_size=0.67)

logistic regression

In [ ]:
# import the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
# training the model
model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression()

In [ ]:
# predicting the outputs
model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# accuracy of the model
model.score(X_test,y_test)

0.7040816326530612

svm model

In [ ]:
# import the model
from sklearn.svm import SVC
model = SVC()

In [ ]:
# training the model
model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [ ]:
# predicting the outputs
model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# accuracy of the model
model.score(X_test,y_test)

0.7040816326530612

In [ ]:
# seperate accurate shot set
accurate_shot_set = df[df.accuracy==1]
accurate_shot_set=accurate_shot_set.drop('accuracy',1)
accurate_shot_set

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,fv.st.hp,fv.bl.hp,fv.ds.hp,fv.im.hp,fv.ft.hp,fsv.st.ba,fsv.st.tha,fsv.st.bha,fsv.st.ff.ka,fsv.st.bf.ka,...,bsv.im.bf.ka,bsv.im.hip.a,bsv.ft.ba,bsv.ft.tha,bsv.ft.bha,bsv.ft.ff.ka,bsv.ft.bf.ka,bsv.ft.hip.a,player,shot
186,1,1,1,1,1,38.049224,173.600701,173.620083,171.785231,177.120230,...,158.285253,170.014743,63.022666,348.509848,3.225897,141.151989,175.945860,174.220420,1,pull
187,1,1,1,1,1,37.049865,172.983701,174.542083,172.647831,178.030230,...,157.315253,171.014743,63.022666,347.752848,2.215897,142.151989,173.945860,172.220420,1,pull
188,1,1,1,1,1,40.011223,174.202701,173.340083,169.227831,178.030230,...,158.315253,172.014743,63.022666,348.509848,1.915897,142.151989,173.945860,173.220420,1,pull
189,1,1,1,1,1,42.480266,172.382701,172.220083,170.437831,178.030230,...,159.315253,171.014743,63.022666,346.509848,2.205897,142.151989,174.945860,171.220420,1,pull
190,1,1,1,1,1,39.062229,173.513708,171.940183,170.286531,176.123230,...,158.285253,170.014743,63.022666,348.509848,2.215897,143.151989,173.945860,172.220420,1,pull
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,1,1,1,1,1,34.456319,171.260633,169.888323,170.741234,169.546227,...,170.043681,169.243327,0.000000,295.921692,0.000000,169.876313,174.015762,178.289155,1,cut
297,1,1,1,1,1,44.049224,179.600701,179.620083,177.785231,183.120230,...,164.285253,176.014743,69.022666,354.509848,9.225897,147.151989,181.945860,180.220420,1,pull
298,1,1,1,1,1,35.049224,170.600701,170.620083,178.785231,174.120230,...,155.285253,167.014743,60.022666,345.509848,0.225897,139.151989,172.945860,171.220420,1,pull
299,1,1,1,1,1,30.686650,194.834498,179.494779,167.341543,184.958215,...,92.921472,159.910785,0.000000,35.903286,299.966121,101.253823,91.247889,157.250527,4,sweep
300,1,1,1,1,1,21.686650,185.834498,170.494779,158.341543,175.958215,...,83.921472,150.910785,0.000000,26.903286,290.966121,92.253823,82.247889,148.250527,4,sweep

In [ ]:
# seperate accurate shot set
inaccurate_shots = df[df.accuracy==0]
inaccurate_shots=inaccurate_shots.drop('accuracy',1)
inaccurate_shots=inaccurate_shots[['fsv.st.ba',
       'fsv.st.tha', 'fsv.st.bha', 'fsv.st.ff.ka', 'fsv.st.bf.ka',
       'fsv.st.hip.a', 'fsv.bl.ba', 'fsv.bl.tha', 'fsv.bl.bha', 'fsv.bl.ff.ka',
       'fsv.bl.bf.ka', 'fsv.bl.hip.a', 'fsv.ds.ba', 'fsv.ds.tha', 'fsv.ds.bha',
       'fsv.ds.ff.ka', 'fsv.ds.bf.ka', 'fsv.ds.hip.a', 'fsv.im.ba',
       'fsv.im.tha', 'fsv.im.bha', 'fsv.im.ff.ka', 'fsv.im.bf.ka',
       'fsv.im.hip.a', 'fsv.ft.ba', 'fsv.ft.tha', 'fsv.ft.bha', 'fsv.ft.ff.ka',
       'fsv.ft.bf.ka', 'fsv.ft.hip.a', 'bsv.st.ba', 'bsv.st.tha', 'bsv.st.bha',
       'bsv.st.ff.ka', 'bsv.st.bf.ka', 'bsv.st.hip.a', 'bsv.bl.ba',
       'bsv.bl.tha', 'bsv.bl.bha', 'bsv.bl.ff.ka', 'bsv.bl.bf.ka',
       'bsv.bl.hip.a', 'bsv.ds.ba', 'bsv.ds.tha', 'bsv.ds.bha', 'bsv.ds.ff.ka',
       'bsv.ds.bf.ka', 'bsv.ds.hip.a', 'bsv.im.ba', 'bsv.im.tha', 'bsv.im.bha',
       'bsv.im.ff.ka', 'bsv.im.bf.ka', 'bsv.im.hip.a', 'bsv.ft.ba',
       'bsv.ft.tha', 'bsv.ft.bha', 'bsv.ft.ff.ka', 'bsv.ft.bf.ka',
       'bsv.ft.hip.a','shot']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
inaccurate_shots.shot.unique()

array(['back foot drive', 'back foot deffence', 'front foot defence',
       'front foot drive', 'sweep', 'pull', 'cut'], dtype=object)

In [ ]:
import pandas as pd
import numpy as np

cols=['fsv.st.ba','fsv.st.tha', 'fsv.st.bha', 'fsv.st.ff.ka', 'fsv.st.bf.ka',
       'fsv.st.hip.a', 'fsv.bl.ba', 'fsv.bl.tha', 'fsv.bl.bha', 'fsv.bl.ff.ka',
       'fsv.bl.bf.ka', 'fsv.bl.hip.a', 'fsv.ds.ba', 'fsv.ds.tha', 'fsv.ds.bha',
       'fsv.ds.ff.ka', 'fsv.ds.bf.ka', 'fsv.ds.hip.a', 'fsv.im.ba',
       'fsv.im.tha', 'fsv.im.bha', 'fsv.im.ff.ka', 'fsv.im.bf.ka',
       'fsv.im.hip.a', 'fsv.ft.ba', 'fsv.ft.tha', 'fsv.ft.bha', 'fsv.ft.ff.ka',
       'fsv.ft.bf.ka', 'fsv.ft.hip.a', 'bsv.ds.bha', 'bsv.ds.ff.ka',
       'bsv.ds.bf.ka', 'bsv.ds.hip.a', 'bsv.im.tha', 'bsv.im.bha',
       'bsv.im.ff.ka', 'bsv.im.bf.ka', 'bsv.im.hip.a', 'bsv.ft.ba',
       'bsv.ft.tha', 'bsv.ft.bha', 'bsv.ft.ff.ka', 'bsv.ft.bf.ka',
       'bsv.ft.hip.a']
       
df = pd.read_excel('module_2.xlsx')
correct = df[df['correctness']==1]
incorrect = df[df['correctness']==0]
aggs = correct.groupby('shot').agg(['min', 'max', 'mean'])

In [ ]:
def calculate(col_name, col_val, shot):
  global aggs
  if col_val >= aggs[col_name]['min'][shot] and col_val <= aggs[col_name]['max'][shot]:
    return 0
  else:
    return (aggs[col_name]['mean'][shot] - col_val)

for col in cols:
  incorrect[col] = df.apply(lambda row : calculate(col, row[col],row['shot']), axis = 1)

incorrect.to_csv('output.csv')
incorrect

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,fv.st.hp,fv.bl.hp,fv.ds.hp,fv.im.hp,fv.ft.hp,fsv.st.ba,fsv.st.tha,fsv.st.bha,fsv.st.ff.ka,fsv.st.bf.ka,...,bsv.im.hip.a,bsv.ft.ba,bsv.ft.tha,bsv.ft.bha,bsv.ft.ff.ka,bsv.ft.bf.ka,bsv.ft.hip.a,player,shot,correctness
0,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,1,back foot drive,0
1,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,1,back foot drive,0
2,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,1,back foot drive,0
3,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,1,back foot drive,0
4,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,1,back foot drive,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,18.293841,0.0,0.0,0.0,0.0,0.0,19.856661,1,pull,0
283,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,16.293841,0.0,0.0,0.0,0.0,0.0,17.856661,1,pull,0
284,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,18.642857,1,cut,0
285,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,19.642857,1,cut,0
286,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,20.642857,1,cut,0